[theme]
base                     = "dark"
primaryColor             = "#7c3aed"
backgroundColor          = "#1a1a1a"
secondaryBackgroundColor = "#242424"
textColor                = "#d4d4d4"
font                     = "sans serif"

[client]
toolbarMode              = "minimal"
